apiVersion: v1
kind: Pod
metadata:
  name: flux-test-pod
  namespace: default
  labels:
    app: flux-test
spec:
  containers:
    - name: flux-test-container
      image: nginx:latest
      ports:
        - containerPort: 80
      resources:
        limits:
          memory: "128Mi"
          cpu: "500m"
        requests:
          memory: "64Mi"
          cpu: "250m"
